### ISSUE TITLE
I _think_ the presence simulation component does not remove the automations once it gets uninstalled.

### ISSUE THREAD

**Issue by jnmoons** [slashback100/presence_simulation#46]
Thanks for the integration. I found it really useful.

I _think_ the presence simulation integration does not remove the automations it creates once it gets uninstalled. I removed the integrations, and the lights turn on and off based on the delay. I could not trace it back to other automations I have running still. I also do not see a way to remove these automations now, so my lights keep turning on and off. Is there any way to remedy this now?

Ideas for the future: Being able to choose multiple lights at once using checkboxes would greatly increase the user friendliness

**Comment by slashback100** [comment]
I don't see any method that would be called by HA when uninstalling the component, so I don't thing there is currently a way for to make sure the simulation is off before the un-installation...

**Comment by JanMoonsUGent** [comment]
Ok, but now I am left with an automation that continues to run, and there does not seem to remove it at all, or even see what automations were created. Surely I don't have to completely restart my HA installation from scratch? Is there a way to see what was created, and can these automations be removed manually?

**Comment by JanMoonsUGent** [comment]
I just removed it from HACS again. It said: "Integration is configured

The Presence Simulation integration is configured, you need to delete the configuration for it before removing it from HACS" and had a chance to either ignore or navigate. This time I chose ignore. Last time not, so I assume it did not uninstall completely. Now the folder is also gone from custom components. Hope this solves it. Can you confirm that if the code is gone, there should no longer be any automations generated by the simulation that keep on running after the uninstallation? I.e. --> the code generates the automations on demand, rather than through any sort of repeateted automation?

**Comment by slashback100** [comment]
Yes, if you remove the code of the custom component and restart HA, nothing will be run by the component anymore
