### ISSUE TITLE
Question: Possible to add more details to the logbook?

### ISSUE THREAD

**Issue by h4nnes** [slashback100/presence_simulation#74]
Hi,
is it possible to add more details to the logbook when e.g. a light gets turned on by the simulation? Sometime I'm wondering why my light was on and nobody was at home and then I realize that the simulation was on ^^

**Comment by ScanlanGP** [comment]
> Hi, is it possible to add more details to the logbook when e.g. a light gets turned on by the simulation? Somethime I'm wondering why my light was on and nobody was at home and then I realize that the simulation was on ^^


I agree. That would be great!

**Comment by slashback100** [comment]
I'm not sure I can do that... I am expecting the logbook to be updated when the `turn_on`/`turn_off` services are called. If it is not (I actually never checked), I don't see what I can do... I'll take a look

**Comment by redlefloh** [comment]
What would also be great is a simulation of the simulation, i.e. a boolean flag that says just simulate the presence simulation and instead of actually turning the lights or switches on and off, it would either just write a log entry or even better one could get a notification with a notify.xxx when a device gets turned on or off by the presence simulation, that way one would get confidence that the simulation actually works as intended before using it without messing up the normal use since when the presence simulation is actually on, one is typically not at home and therefore can't observe the actual behavior... 😉 Thanks!

**Comment by slashback100** [comment]
@redlefloh in v3.3 (just released), I added an event `presence_simulation_change` that is triggered when the simulation calls a service (turn on a light, open a cover...). That way you can create an automation that will notify you when it does something.

**Comment by redlefloh** [comment]
@slashback100 fantastic, thanks so much, I'll take it for a spin once it is pushed to HACS! But it sounds like this will allow me to monitor only when the presence simulation is actually active, it would be great to also have an event that would trigger when the presence simulation would turn on a switch or light but it would not actually do so, so one can simulate the presence simulation before it is needed and then one see if everything would work as intended (as opposed to monitoring that it works as intended)?

**Comment by redlefloh** [comment]
@slashback100 I tested the new event with some devices that don't disturb the rest of the family 😉 and with presence simulation active. The event works great, including brightness, and also after rebooting HA and this now gives me the confidence to just add my regular lights and devices to the presence simulation light group for the next vacation trip. Thanks again, coffee (or rather 🍻) has been bought!

**Comment by slashback100** [comment]
Thanks 😄
