### ISSUE TITLE
Possible to add multiple switch entities?

### ISSUE THREAD

**Issue by mngsps** [slashback100/presence_simulation#95]
Hi @slashback100 ,
at first, thank you so much for this great work!
One question: Is or would it be possible to add and configure multiple presence simulation switches (e.g. to have separate ones for lights, covers or different floors/rooms)? I tried, but the second one will not create a switch entity in my case...
All the best and kind regards
Benedikt

**Comment by slashback100** [comment]
It has been asked in #27.
I can take a look to see how to do that, but it seems like an important architecture change

**Comment by slashback100** [comment]
Just created a branch `manage_multiple_switches` with this feature. Don't know if you can test it, in particular the migration from old to new version

**Comment by tomrennen** [comment]
Hi @slashback100, hopefully you're still following up on this:

I've now activated the `manage_multiple_switches` variant on my prod environment (Because I really want this feature). My specific setup is:
- Presence Simulation Lights -> Couple of lights
- Presence Simulation Covers -> Just 2 covers (I don't want these to trigger, read: wake the kids, while we're not actually gone)

Now I've gone ahead and deleted the old presence simulation (I'll test migration later, but I want to test with clean slate first), then installed the `manage_multiple_switches` branch.

What I saw:
1. The second presence simulation switch was unavailable until a restart
2. When activating just the "Lights" PS, the attributes show next event being closing cover_0001:
<table> 
<tr>
<td><img src="https://github.com/slashback100/presence_simulation/assets/14904652/dd02b9de-31bb-45d4-809d-ed7cf841e73b" width=400 /></td>
<td><img src="https://github.com/slashback100/presence_simulation/assets/14904652/6cfe6ba4-119d-4175-ba6b-5cc83f217d01" width=400 /> </td>
</tr>
</table>
This actually is applied: the covers were closed even though it was disabled for the "Covers" variant.

**Comment by slashback100** [comment]
Yes, still working on it but can't figure out why the entities are unavailable...

**Comment by slashback100** [comment]
Got this problem fixed. Working now on the mix up between switches

**Comment by slashback100** [comment]
There you go. I fixed the issue, which included a refactoring of the restore after restart feature. My tests give good results.
Everything is in branch  manage_multiple_switches, I created a [PR ](https://github.com/slashback100/presence_simulation/pull/110)
I just need to test the migration from a v3 to this v4 still.

**Comment by slashback100** [comment]
I tested the migration. It works, but since the logic changes, the id of the switch entity changes --> a new entity will be created (`switch.presence_simulation_2`) and the previous one will be unavailable. 
I don't see any solution, it is kind of breaking change.
I will merge on the main, but won't do any release for now, I will be on holiday so don't have time for fixing issues.

**Comment by slashback100** [comment]
FYI I managed to avoid the breaking change in the migration

**Comment by slashback100** [comment]
Release has been done : https://github.com/slashback100/presence_simulation/releases/tag/v4.0
